use GuestAdditionsVersion from VBoxManage; VMStateChangeTime compared literally so a lot faster; Moved normal case almost to top so much faster

diff --git a/bin/bivio_vagrant_ssh b/bin/bivio_vagrant_ssh
--- a/bin/bivio_vagrant_ssh
+++ b/bin/bivio_vagrant_ssh
@@ -6,137 +6,84 @@
 # Also gives us a hook for checking guest additions
 #
 
-# What we execute to start ssh efficiently
-ssh_file=.vagrant/.bivio.ssh
+# State between runs
+state_file=.vagrant/.bivio_vagrant_ssh.sh
 
-# Where ssh outputs errors (below)
-ssh_err_file=.vagrant/.bivio.ssh_err
-
-# Where we cache version
-version_file=.vagrant/.bivio.host_version
+# Load stored state
+. "$state_file" 2>/dev/null
 
 # Computed host version
 host_version=$(perl -e 'print((`VBoxManage --version` =~ /^([\d\.]+)/)[0])')
 
-err_exit() {
-    echo "$1"
-    if [[ $2 ]]; then
-        cat "$2"
-    fi
-    exit 1
-}
-
-empty_cache() {
-    rm -f "$ssh_file" "$version_file" "$ssh_err_file"
-}
-
-is_running() {
+check_vm_state() {
     local vbox_id=$(cat .vagrant/machines/default/virtualbox/id 2>/dev/null)
     if [[ ! $vbox_id ]]; then
         return 1
     fi
-    eval $(VBoxManage showvminfo "$vbox_id" --machinereadable 2>/dev/null | grep -s '^VMState')
-    [[ $VMState == running ]]
+    eval $(VBoxManage showvminfo "$vbox_id" --machinereadable 2>/dev/null | egrep -s '^(VMState|GuestAdditionsVersion)')
+    guest_version=${GuestAdditionsVersion% *}
+    is_running=
+    if [[ $VMState == running ]]; then
+        is_running=1
+    fi
 }
 
 exec_ssh() {
-    exec $(cat $ssh_file) "$@"
-    empty_cache
-    err_exit 'Something went seriously wrong. Try "vagrant ssh" or "vagrant status"'
+    exec $ssh_cmd "$@"
+    echo 'Something went seriously wrong. Try "vagrant ssh" or "vagrant status"' 1>&2
+    exit 1
+}
+
+# Normal case up front so runs the fastest
+check_vm_state
+if [[ $is_running && $ssh_cmd \
+            && $last_vm_boot == $VMStateChangeTime \
+            && $host_version == $guest_version ]]; then
+    exec_ssh "$@"
+fi
+
+#
+# All the special cases are below
+#
+
+# Where ssh outputs errors (below)
+ssh_err_file=.vagrant/.bivio_vagrant_ssh.log
+
+err_exit() {
+    user_msg "$1"
+    if [[ ! -z $ssh_err_file ]]; then
+        cat "$ssh_err_file"
+    fi
+    exit 1
 }
 
 user_msg() {
     echo "$1" 1>&2
 }
 
-is_ssh_file_ok() {
-    if [[ ! -f $ssh_file ]]; then
-        return 1
-    fi
-    # VMStateChangeTime is full ISO, e.g. 2015-04-23T01:08:04.000000000
-    # Hopefully, Time::Local is on all systems by now
-    perl - "$VMStateChangeTime" "$ssh_file" <<'EOF'
-use Time::Local;
-@x = $ARGV[0] =~ /(\d+)/g;
-pop(@x);
---$x[1];
-exit(timegm(reverse(@x)) < (stat($ARGV[1]))[9] ? 0 : 1);
-EOF
-}
-
 if [[ ! $host_version ]]; then
-    err_exit 'VBoxManage needs to be in path to work'
+    err_exit 'VBoxManage needs to be in $PATH to work.'
 fi
 
-if ! is_running; then
-    if [[ ! -f Vagrantfile ]]; then
-        err_exit 'You need to initialize vagrant, e.g. "vagrant init radiasoft/fedora"'
-    fi
+if [[ ! -f Vagrantfile ]]; then
+    err_exit 'You need to initialize vagrant, e.g. "vagrant init radiasoft/fedora"'
+fi
 
+if [[ ! $is_running ]]; then
     user_msg 'VM not running. Booting... (may take a few minutes)'
-    # This may fail due to a guest update problem.
+    # This may fail due to a guest update problem so we have to check running
     vagrant up
-    empty_cache
-    if ! is_running; then
+    check_vm_state
+    if [[ ! $is_running ]]; then
         err_exit 'Unable to boot VM (see above)'
     fi
-
-elif [[ -f $version_file && $(cat $version_file) != $host_version ]]; then
-    empty_cache
-
-elif is_ssh_file_ok; then
-    exec_ssh "$@"
 fi
 
-user_msg 'Verifying VirtualBox software is up to date ... (may take a few seconds)'
-
-check_guest_version() {
-    vagrant ssh -c 'VBoxControl --version; sleep 1' > $ssh_err_file 2>&1 < /dev/null &
-    child=$!
-    declare -i i=0
-    while (( $i < 6 )); do
-        cmd="$(ps axww | grep ' ssh vagrant@.*VBoxControl' | grep -v ' grep ')"
-        if [[ $cmd ]]; then
-            break
-        fi
-        sleep 1
-    done
-
-    if [[ ! $cmd ]]; then
-        err_exit 'Unable to access virtual machine:' "$ssh_err_file"
-    fi
-
-    i=0
-    while ps "$child" &>/dev/null; do
-        if (( $i > 5 )); then
-            kill -9 "$child"
-            err_exit 'Software check failed:'  "$ssh_err_file"
-        fi
-        sleep 1
-        i+=1
-    done
-
-    guest_version=$(perl -n -e '/^(\d+\.\d+\.\d+)/ && print($1) && exit(0)' "$ssh_err_file")
-    if [[ ! $guest_version ]]; then
-        if ! grep -s -q 'VBoxControl: command not found' "$ssh_err_file"; then
-            err_exit 'Unable to extract guest version from VBoxControl --version:' "$ssh_err_file"
-        fi
-        # No VBoxControl, no guest additions, do fresh install
-        guest_version=''
-    fi
-
-    cmd=${cmd#* ssh }
-    # Obviously only works with Unix hosts
-    cmd="ssh ${cmd% -t bash -l*}"
-    # FATAL outputs nothing on error so switch to ERROR
-    cmd=${cmd/LogLevel=FATAL/LogLevel=ERROR}
-}
-
-check_guest_version
 if [[ $guest_version != $host_version ]]; then
-    user_msg 'VirtualBox "guest" software is out of date; Updating ... (may take tens of minutes)'
+    user_msg 'VirtualBox guest software needs updating ... (may take tens of minutes)'
     update_script=.vbox-guest-update.sh
-    $cmd "dd of='$update_script'" <<'EOF'
+    vagrant ssh -c "dd of='$update_script'; sudo host_version='$host_version' bash '$update_script'" <<'EOF'
+rm -f "${BASH_SOURCE[0]}"
 iso=VBoxGuestAdditions_$host_version.iso
 
 clean_up() {
@@ -151,7 +98,7 @@ trap clean_up EXIT
 #TODO(robnagler) Is this robust enough?
 rpms=$(rpm -qa | grep VirtualBox)
 if [[ $rpms ]]; then
-    yum remove -y $rpms || true
+    yum remove -y -q $rpms || true
 fi
 
 set -e
@@ -166,19 +113,58 @@ mount -t iso9660 -o loop,rw "$iso" /mnt
 # have a failure anyway.
 sh /mnt/VBoxLinuxAdditions.run < /dev/null || true
 EOF
-    if ! $cmd "sudo host_version='$host_version' bash '$update_script'"; then
-        err_exit 'Upgrade failed. See output' "$ssh_err_file"
+    if (( $? != 0 )); then
+        err_exit 'Upgrade failed. See output'
     fi
     user_msg 'Rebooting virtual machine... (may take a few minutes)'
     vagrant reload
-    check_guest_version
+    check_vm_state
+    if [[ ! $is_running ]]; then
+        err_exit 'Unable to reload VM (see above)'
+    fi
     if [[ $guest_version != $host_version ]]; then
         err_exit 'Unable to update VirtualBox guest software.'
     fi
 fi
 
-echo -n "$host_version" > "$version_file"
-echo -n "$cmd" > "$ssh_file"
+user_msg 'Extracting virtual machine ssh command ... (may take a few seconds)'
+
+vagrant ssh -c 'sleep 2' > $ssh_err_file 2>&1 < /dev/null &
+child=$!
+declare -i i=0
+while (( $i < 6 )); do
+    ssh_cmd="$(ps axww | grep ' ssh vagrant@.*sleep' | grep -v ' grep ')"
+    if [[ $ssh_cmd ]]; then
+        break
+    fi
+    sleep 1
+done
+
+if [[ ! $ssh_cmd ]]; then
+    err_exit 'Unable to access virtual machine:' "$ssh_err_file"
+fi
+
+i=0
+while ps "$child" &>/dev/null; do
+    if (( $i > 5 )); then
+        kill -9 "$child"
+        err_exit 'Remote process had to be killed:'  "$ssh_err_file"
+    fi
+    sleep 1
+    i+=1
+done
+rm -f "$ssh_err_file"
+
+ssh_cmd=${ssh_cmd#* ssh }
+# Obviously only works with Unix hosts
+ssh_cmd="ssh ${ssh_cmd% -t bash -l*}"
+# FATAL outputs nothing on error so switch to ERROR
+ssh_cmd=${ssh_cmd/LogLevel=FATAL/LogLevel=ERROR}
+
+cat > "$state_file" <<EOF
+ssh_cmd='$ssh_cmd'
+last_vm_boot='$VMStateChangeTime'
+EOF
 
 user_msg 'Starting ssh...'
 
